### ISSUE TITLE
Audit and remove fubarhouse_npm variable object

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/fubarhouse.npm#29]
Variables need refactoring:

````
fubarhouse_npm:
  clean_install: true
  user_dir: /Users/karl/
  nvm_install_dir: /Users/karl/.nvm
  shell_profiles:
  - filename: .bash_profile
  folder_paths:
  - path: "/usr/local/lib/node_modules"
  - path: "/Users/{{ fubarhouse_user }}/.npm"
  - path: "/Users/{{ fubarhouse_user }}/.nvm"
  nvm_repo: "https://github.com/xtuple/nvm.git"
  nvm_symlink_exec: /usr/local/bin/nvm
````
